In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('datasets/properties.csv')

In [3]:
df_bp = df.copy()

In [4]:
df.head(2)

,ID,Possession Status,Availability Starts From,Floor No,Commercial,Developer,Approved Authority Name,Units Available,Price,Price (English),...,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,Possession By,NRI Pref,Land Area / Covered Area,Land Area Unit,Pantry Type
0,12685,Under Construction,Dec '25,5,N,NaN,KDMC,1.0,3150000.0,31.5 Lac,...,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
1,12684,Ready to Move,NaN,20,Y,TATA Housing Development Company Ltd.,TMC,10.0,6300000.0,63 Lac,...,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape, df.drop_duplicates().shape

((12685, 145), (12685, 145))

In [6]:
df.isnull().sum()

ID                              0
Possession Status              78
Availability Starts From     9602
Floor No                      858
Commercial                      0
                            ...
Possession By               12449
NRI Pref                    10668
Land Area / Covered Area    12601
Land Area Unit              12599
Pantry Type                 12620
Length: 145, dtype: int64

In [7]:
df['Developer'] = df['Developer'].fillna('Local')

In [8]:
df['Units Available'] = df['Units Available'].fillna(1)
pct_null = df.isnull().sum() / len(df)
missing_features = pct_null[pct_null >= 0.2].index # dropping columns with >= 20%
df.drop(missing_features, axis=1, inplace=True)

In [9]:
df['Possession Status'].value_counts().to_frame().reset_index()

     Possession Status  count
0        Ready to Move   9735
1   Under Construction   2630
2              Dec '26     50
3              Dec '24     31
4              Dec '23     29
5              Dec '25     28
6              Jun '24     21
7              Dec '27     16
8              Jun '26     16
9              Dec '28     12
10             Mar '25      6
11             Mar '24      5
12             Apr '28      4
13             Sep '26      4
14         Immediately      4
15             Nov '25      3
16             Apr '24      3
17             Jun '25      3
18             Sep '23      3
19             Nov '23      2
20         Select Date      2

In [10]:
df.columns[:40], df.columns[40:80], df.columns[80:]

(Index(['ID', 'Possession Status', 'Floor No', 'Commercial', 'Developer',
        'Units Available', 'Price', 'Price (English)', 'Covered Area',
        'sqft Price ', 'Area Name', 'Unit of Carpet Area', 'Society',
        'furnished Type', 'Bathroom', 'Transaction Type', 'Floor Data',
        'Type of Property', 'City', 'bedroom', 'Data Referred From', 'floors',
        'Luxury Flat', 'Covered Area.1', 'isPrimeLocationProperty',
        'Tenants Preference', 'Location', 'Property', 'covArea Unit',
        'isLuxuryServiceProvided', 'Power Back Up', 'Lift',
        'Rain Water Harvesting', 'Club House', 'Swimming Pool', 'Gymnasium',
        'Park', 'Parking.1', 'Security', 'Water Storage'],
       dtype='object'),
 Index(['Private Terrace/Garden', 'Vaastu Compliant', 'Service/Goods Lift',
        'Air Conditioned', 'Visitor Parking', 'Intercom Facility',
        'Maintenance Staff', 'Waste Disposal', 'Laundry Service',
        'Internet/Wi-Fi Connectivity', 'DTH Television Facility',
        'RO Water System', 'Banquet Hall', 'Bar/Lounge', 'Cafeteria/Food Court',
        'Conference Room', 'Piped Gas', 'Jogging and Strolling Track',
        'Outdoor Tennis Courts', 'Mansion', 'Downtown', 'Skyline View',
        'Wrap Around Balcony', 'Island Kitchen Layout', 'Full Glass Wall',
        'House help accommodation', 'Concierge Services', 'Garden View',
        'Marble flooring', 'Well Furnished', 'Modular Kitchen', 'Helipad',
        'Private pool ', 'Private Jaccuzi', 'Mini Cinema Theatre',
        'Golf Course', 'Infinity Swimming Pool',
        'Pool with temperature control ', 'Sea facing', 'Skydeck'],
       dtype='object'),
 Index(['Earth quake resistant', 'Theme based Architectures',
        'Health club with Steam / Jaccuzi', 'Large Clubhouse ',
        'Large Open space', 'Fingerprint Access', 'Grand Entrance lobby',
        'Private Garage', 'Fireplace', 'Wine Cellar', 'Sky Villa',
        'Water Front', 'Hilltop', 'Smart Home', 'Barbeque space',
        'Kids play area', 'Library', 'Puja Room', 'Study', 'Servant Room',
        'Store', 'Aerobics Room', 'Canopy Walk', 'Coffee Lounge & Restaurants',
        'Dance Studio', 'Event Space & Amphitheatre', 'Flower Gardens',
        'Guest Accommodation', 'Indoor Squash & Badminton Courts',
        'Kids Play Area', 'Kids Play Pool With Water Slides',
        'Library And Business Centre', 'Meditation Area', 'Multipurpose Courts',
        'Recreational Pool', 'Rentable CommuniPfty Space',
        'Retail Boulevard (Retail Shops)', 'Cycling & Jogging Track',
        'Fire Fighting Equipment', 'Aesthetically designed landscape garden'],
       dtype='object'))

In [11]:
df = df[df['City'].isin(['Mumbai', 'Thane'])]
df.reset_index(drop=True, inplace=True)
df.drop('City', axis=1, inplace=True)

In [12]:
df.rename(columns={'Property':'Property BHK Type', 'Parking.1':'Parking', 'sqft Price ':'Price per square feet', 'isPrimeLocationProperty':'Prime location'}, inplace=True)

In [13]:
df = df[df['Possession Status'].isin(['Ready to Move', 'Under Construction'])]
df.reset_index(drop=True, inplace=True)

In [14]:
df.shape

(12335, 119)

In [15]:
df['Area Name'].value_counts()[:20], df['Location'].value_counts()[:20]

(Area Name
 Dombivli East     653
 Andheri West      479
 Malad East        466
 Thane West        427
 Andheri East      425
 Kandivali West    356
 Kolshet Road      320
 Majiwada          310
 Goregaon East     278
 Mira Road East    278
 Kandivali East    276
 Virar West        241
 Manpada           230
 Prabhadevi        212
 Kalyan West       202
 Balkum village    188
 Dahisar East      185
 Santacruz West    185
 Naigaon East      176
 Dadar West        160
 Name: count, dtype: int64,
 Location
 Dombivli East, Thane      641
 Andheri West, Mumbai      467
 Malad East, Mumbai        454
 Thane West, Thane         417
 Andheri East, Mumbai      410
 Kandivali West, Mumbai    345
 Kolshet Road, Thane       318
 Majiwada, Thane           310
 Mira Road East, Mumbai    278
 Goregaon East, Mumbai     276
 Kandivali East, Mumbai    273
 Virar West, Mumbai        237
 Manpada, Thane            220
 Prabhadevi, Mumbai        211
 Kalyan West, Thane        199
 Balkum village, Thane     188
 Santacruz West, Mumbai    185
 Dahisar East, Mumbai      182
 Naigaon East, Mumbai      169
 Dadar West, Mumbai        158
 Name: count, dtype: int64)

In [16]:
df.drop(['Data Referred From', 'Covered Area.1', 'covArea Unit', 'isLuxuryServiceProvided', 'Location', 'Commercial', 'Floor No', 'floors'], axis=1, inplace=True)

In [17]:
df.columns[:40], df.columns[40:80], df.columns[80:]

(Index(['ID', 'Possession Status', 'Developer', 'Units Available', 'Price',
        'Price (English)', 'Covered Area', 'Price per square feet', 'Area Name',
        'Unit of Carpet Area', 'Society', 'furnished Type', 'Bathroom',
        'Transaction Type', 'Floor Data', 'Type of Property', 'bedroom',
        'Luxury Flat', 'Prime location', 'Tenants Preference',
        'Property BHK Type', 'Power Back Up', 'Lift', 'Rain Water Harvesting',
        'Club House', 'Swimming Pool', 'Gymnasium', 'Park', 'Parking',
        'Security', 'Water Storage', 'Private Terrace/Garden',
        'Vaastu Compliant', 'Service/Goods Lift', 'Air Conditioned',
        'Visitor Parking', 'Intercom Facility', 'Maintenance Staff',
        'Waste Disposal', 'Laundry Service'],
       dtype='object'),
 Index(['Internet/Wi-Fi Connectivity', 'DTH Television Facility',
        'RO Water System', 'Banquet Hall', 'Bar/Lounge', 'Cafeteria/Food Court',
        'Conference Room', 'Piped Gas', 'Jogging and Strolling Track',
        'Outdoor Tennis Courts', 'Mansion', 'Downtown', 'Skyline View',
        'Wrap Around Balcony', 'Island Kitchen Layout', 'Full Glass Wall',
        'House help accommodation', 'Concierge Services', 'Garden View',
        'Marble flooring', 'Well Furnished', 'Modular Kitchen', 'Helipad',
        'Private pool ', 'Private Jaccuzi', 'Mini Cinema Theatre',
        'Golf Course', 'Infinity Swimming Pool',
        'Pool with temperature control ', 'Sea facing', 'Skydeck',
        'Earth quake resistant', 'Theme based Architectures',
        'Health club with Steam / Jaccuzi', 'Large Clubhouse ',
        'Large Open space', 'Fingerprint Access', 'Grand Entrance lobby',
        'Private Garage', 'Fireplace'],
       dtype='object'),
 Index(['Wine Cellar', 'Sky Villa', 'Water Front', 'Hilltop', 'Smart Home',
        'Barbeque space', 'Kids play area', 'Library', 'Puja Room', 'Study',
        'Servant Room', 'Store', 'Aerobics Room', 'Canopy Walk',
        'Coffee Lounge & Restaurants', 'Dance Studio',
        'Event Space & Amphitheatre', 'Flower Gardens', 'Guest Accommodation',
        'Indoor Squash & Badminton Courts', 'Kids Play Area',
        'Kids Play Pool With Water Slides', 'Library And Business Centre',
        'Meditation Area', 'Multipurpose Courts', 'Recreational Pool',
        'Rentable CommuniPfty Space', 'Retail Boulevard (Retail Shops)',
        'Cycling & Jogging Track', 'Fire Fighting Equipment',
        'Aesthetically designed landscape garden'],
       dtype='object'))

In [18]:
df.shape

(12335, 111)

In [19]:
for i in df.columns:
    df[i] = df[i].fillna(df[i].mode()[0])

In [20]:
for i in ['Society', 'furnished Type',
        'Bathroom', 'Transaction Type', 'Floor Data', 'Type of Property',
        'bedroom', 'Luxury Flat', 'Prime location',
        'Tenants Preference', 'Property BHK Type', 'Power Back Up', 'Lift',
        'Rain Water Harvesting', 'Club House', 'Swimming Pool', 'Gymnasium',
        'Park', 'Parking', 'Security', 'Water Storage',
        'Private Terrace/Garden', 'Vaastu Compliant', 'Service/Goods Lift',
        'Air Conditioned', 'Visitor Parking', 'Intercom Facility',
        'Maintenance Staff', 'Waste Disposal', 'Laundry Service', 'Internet/Wi-Fi Connectivity',
        'DTH Television Facility', 'RO Water System', 'Banquet Hall',
        'Bar/Lounge', 'Cafeteria/Food Court', 'Conference Room', 'Piped Gas',
        'Jogging and Strolling Track', 'Outdoor Tennis Courts', 'Mansion',
        'Downtown', 'Skyline View', 'Wrap Around Balcony',
        'Island Kitchen Layout', 'Full Glass Wall', 'House help accommodation',
        'Concierge Services', 'Garden View', 'Marble flooring',
        'Well Furnished', 'Modular Kitchen', 'Helipad', 'Private pool ',
        'Private Jaccuzi', 'Mini Cinema Theatre', 'Golf Course',
        'Infinity Swimming Pool', 'Pool with temperature control ',
        'Sea facing', 'Skydeck', 'Earth quake resistant',
        'Theme based Architectures', 'Health club with Steam / Jaccuzi',
        'Large Clubhouse ', 'Large Open space', 'Fingerprint Access',
        'Grand Entrance lobby', 'Private Garage', 'Fireplace', 'Wine Cellar', 'Sky Villa',
        'Water Front', 'Hilltop', 'Smart Home', 'Barbeque space',
        'Kids play area', 'Library', 'Puja Room', 'Study', 'Servant Room',
        'Store', 'Aerobics Room', 'Canopy Walk', 'Coffee Lounge & Restaurants',
        'Dance Studio', 'Event Space & Amphitheatre', 'Flower Gardens',
        'Guest Accommodation', 'Indoor Squash & Badminton Courts',
        'Kids Play Area', 'Kids Play Pool With Water Slides',
        'Library And Business Centre', 'Meditation Area', 'Multipurpose Courts',
        'Recreational Pool', 'Rentable CommuniPfty Space',
        'Retail Boulevard (Retail Shops)', 'Cycling & Jogging Track',
        'Fire Fighting Equipment', 'Aesthetically designed landscape garden']:
    if(df[i].dtype != 'object'):
        df[i] = np.where(df[i] == 1, i + ', ', '')
    else:
        df[i] = np.where(df[i] == 'Y', i + ', ', df[i])
        df[i] = np.where(df[i] == 'N', '', df[i])

cols = ['Society', 'furnished Type',
        'Bathroom', 'Transaction Type', 'Floor Data', 'Type of Property',
        'bedroom', 'Luxury Flat', 'Prime location',
        'Tenants Preference', 'Property BHK Type', 'Power Back Up', 'Lift',
        'Rain Water Harvesting', 'Club House', 'Swimming Pool', 'Gymnasium',
        'Park', 'Parking', 'Security', 'Water Storage',
        'Private Terrace/Garden', 'Vaastu Compliant', 'Service/Goods Lift',
        'Air Conditioned', 'Visitor Parking', 'Intercom Facility',
        'Maintenance Staff', 'Waste Disposal', 'Laundry Service', 'Internet/Wi-Fi Connectivity',
        'DTH Television Facility', 'RO Water System', 'Banquet Hall',
        'Bar/Lounge', 'Cafeteria/Food Court', 'Conference Room', 'Piped Gas',
        'Jogging and Strolling Track', 'Outdoor Tennis Courts', 'Mansion',
        'Downtown', 'Skyline View', 'Wrap Around Balcony',
        'Island Kitchen Layout', 'Full Glass Wall', 'House help accommodation',
        'Concierge Services', 'Garden View', 'Marble flooring',
        'Well Furnished', 'Modular Kitchen', 'Helipad', 'Private pool ',
        'Private Jaccuzi', 'Mini Cinema Theatre', 'Golf Course',
        'Infinity Swimming Pool', 'Pool with temperature control ',
        'Sea facing', 'Skydeck', 'Earth quake resistant',
        'Theme based Architectures', 'Health club with Steam / Jaccuzi',
        'Large Clubhouse ', 'Large Open space', 'Fingerprint Access',
        'Grand Entrance lobby', 'Private Garage', 'Fireplace', 'Wine Cellar', 'Sky Villa',
        'Water Front', 'Hilltop', 'Smart Home', 'Barbeque space',
        'Kids play area', 'Library', 'Puja Room', 'Study', 'Servant Room',
        'Store', 'Aerobics Room', 'Canopy Walk', 'Coffee Lounge & Restaurants',
        'Dance Studio', 'Event Space & Amphitheatre', 'Flower Gardens',
        'Guest Accommodation', 'Indoor Squash & Badminton Courts',
        'Kids Play Area', 'Kids Play Pool With Water Slides',
        'Library And Business Centre', 'Meditation Area', 'Multipurpose Courts',
        'Recreational Pool', 'Rentable CommuniPfty Space',
        'Retail Boulevard (Retail Shops)', 'Cycling & Jogging Track',
        'Fire Fighting Equipment', 'Aesthetically designed landscape garden']

df['Description/Amenities'] = df[cols].apply(lambda row: ' '.join(row.values.astype(str)), axis=1)
# df.drop(cols, axis=1, inplace=True)

In [13]:
df['Property BHK Type'] = df['Property BHK Type'].apply(lambda x: x.replace(' Flat',''))

In [21]:
df.head(1)

,ID,Possession Status,Developer,Units Available,Price,Price (English),Covered Area,Price per square feet,Area Name,Unit of Carpet Area,...,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,Description/Amenities
0,12685,Under Construction,Local,1.0,3150000.0,31.5 Lac,635.0,4960.0,Kalyan West,Sq-ft,...,"Library And Business Centre,","Meditation Area,","Multipurpose Courts,","Recreational Pool,","Rentable CommuniPfty Space,","Retail Boulevard (Retail Shops),","Cycling & Jogging Track,","Fire Fighting Equipment,","Aesthetically designed landscape garden,","Society, Unfurnished New Property 5 of 14 Fl..."

In [23]:
df['Price per square feet']

0         4960.0
1        10880.0
2         6352.0
3         8571.0
4         8824.0
          ...
12330    20998.0
12331    22529.0
12332    19072.0
12333    26796.0
12334    27007.0
Name: Price per square feet, Length: 12335, dtype: float64

In [3]:
df = df[df['Possession Status'].isin(['Ready to Move', 'Under Construction'])]
df.reset_index(drop=True, inplace=True)
df = df[df['Price'] <= 50000000]
df.reset_index(drop=True, inplace=True)
df = df[df['Units Available'] > 0]
df.reset_index(drop=True, inplace=True)

In [5]:
# df.to_csv('Datasets/property_list.csv', index=False)

In [30]:
str(list(df['Area Name'].unique()))

"['Kalyan West', 'Bhoiwada', 'Rambaug Lane Number 4', 'Kalyan East', 'Chakki Naka', 'Nandivali Gaon', 'Tisgaon Naka', 'Oshiwara', 'Bandivali', 'Jogeshwari West', 'Malcom Baug', 'Amrut Nagar', 'Behram Baug', 'Indira Nagar', 'Jogeshwari Vikhroli Link Road', 'Jogeshwari East', 'Majas Wadi', 'Natwar Nagar', 'Hind Nagar', 'Sham Nagar', 'Dombivli East', 'Sonar Pada', 'Nandivli', 'Desai Village', 'Tilak Nagar', 'Gandhi Nagar Dombivli', 'Usarghar Gaon', 'Dahisar West', 'Kandarpada', 'Mhatre Wadi', 'Gomant Nagar', 'Leo Peter Wadi', 'Shanti Ashram', 'Navagaon', 'Ashok Van', 'Dahisar East', 'Anand Nagar', 'Vaishali Nagar Dahisar', 'Janta Nagar', 'Vaishali Nagar', 'Rawal Pada', 'Maratha Colony Dahisar', 'Shakti Nagar', 'Ketki Pada', 'NL Complex', 'Ghartan Pada', 'Balaji Nagar', 'Waghdevi Nagar', 'Virar West', 'Bolinj', 'Chikhal Dongari', 'Agashi', 'Tirupati Nagar', 'Y K Nagar', 'Gokul Township', 'Virat Nagar', 'Yashavant Nagar', 'Grant Road', 'Virar East', 'Bhalchandra Nagar', 'Dadar West', 'Shivaji Park', 'Kaka Sahab Dadarkar Chowk', 'Chandrakant Dhuru Wadi', 'Kabutarkhana Purandare Chowk', 'Prabodhankar Thakre Chowk', 'Bhawani Shankar', 'Jakhadevi Chowk', 'Suryavanshi Kshatriya Sabhagruha Chowk', 'Vile Parle West', 'Gulmohar Road', 'Suresh Colony', 'Irla', 'Sanyas Ashram Chowk', 'Kamla Nagar', 'Vile Parle East', 'Air India Colony', 'Shahaji Raje Marg', 'Parle Colony', 'Vasai West', 'Suyog Nagar', 'Chulne', 'Dindayal Nagar Vasai', 'Vasai East', 'Golani Naka', 'Dhumal Nagar', 'Kolshet Road', 'Pokharan Road Number 2', 'Balkum village', 'Majiwada', 'Kolshet', 'Manpada', 'Dhokali', 'Hiranandani Estate', 'Bhayandarpada', 'Vasant Vihar', 'Thane West', 'Panch Pakhdi', 'Teen Hath Naka', 'Patlipada', 'Naupada', 'Brahmand', 'Waghbil', 'Balkum Naka', 'Owale', 'Koliwada', 'Kolbad', 'Vartak Nagar', 'Savarkar Nagar', 'Vrindavan Society', 'Anand Nagar Thane West', 'Khopat', 'Pokharan Road Number 1', 'Kapurbawdi', 'Lok Puram', 'Shivai Nagar', 'Charai', 'Ram Maruti Road Naupada', 'Rabodi', 'Dhobi Ali', 'Wagle Industrial Estate', 'Mahagiri Koliwada', 'Lokmanya Nagar', 'Pawar Nagar', 'Uthalsar', 'Jambli Naka', 'Shivaji Nagar', 'Bhaskar Colony', 'Vishnu Nagar', 'Louis Wadi', 'Yashodhan Nagar', 'Gawand Baug', 'Meenatai Thakrey Chowk', 'Raunak Park', 'Runwal Nagar', 'Ghantali', 'Talav Pali', 'Vijay Nagar', 'Hariniwas Circle', 'Kopri', 'Thane East', 'Sion West', 'Chembur East', 'Sion East', 'Sion Koliwada', 'Santacruz West', 'Hasmukh Nagar', 'Willingdon Colony', 'North Ave', 'Saraswat Colony', 'MSES Colony', 'Potohar Nagar', 'Vithaldas Nagar', 'Dadar East', 'Hindu Colony', 'Dadar TT Circle', 'Mancharji Edhalji Joshi Chowk', 'AP Narayan Chowk', 'L Tilak Colony', 'Santacruz East', 'Kalina', 'Vidya Nagari', 'Sen Nagar', 'Kranti Nagar', 'Sundar Nagar, Kalina', 'Prabhat Colony', 'Kolivary', 'Anand Nagar Santacruz East', 'Prabhadevi', 'Adv RD Kowte Chowk', 'Century Bazaar', 'Shree Siddhivinayak Mandir Chowk', 'Babar Shaikh Chowk', 'Mira Road East', 'Mahajan Wadi', 'Geeta Nagar Mira Road', 'Penkarpada', 'Miragaon', 'Nalasopara West', 'Laxmiben Chheda Nagar', 'Samel Pada', 'Nalasopara East', 'Oswal Nagari', 'Naigaon West', 'Naigaon East', 'Goregaon East', 'Gokuldham', 'Film City Road', 'Jayprakash Nagar', 'Bimbisar Nagar', 'Ganesh Nagar', 'Kanya Pada', 'Laxmi Nagar', 'Nagari Nivara Parishad', 'Mali Nagar', 'Sai Baba Complex', 'Aarey Milk Colony', 'NNP Colony', 'Royal Palms Estate', 'Pandurang Wadi', 'Subhash Nagar', 'Churi Wadi', 'Azad Nagar', 'Shreyas Colony', 'Durgeshwari Welfare Society', 'Film City', 'Yeshodham', 'Indian Oil Nagar- Shivaji Nagar', 'Ram Nagar', 'CAMA Industrial Estate', 'Yashodham', 'ITT Bhatti', 'Vishveshwar Nagar', 'Agripada', 'Mumbai Central', 'RTO Colony', 'Churchgate', 'Matunga West', 'Joshi Wadi', 'Mahalaxmi Sindhi Colony', 'S Haralayya Chowk', 'Matunga East', 'Brhmanwada', 'Five Gardens', 'Kings Circle', 'Marine Lines East', 'Marine Lines', 'Churchgate station', 'Marine Drive', 'Malad East', 'Pathanwadi', 'Kurar Village', 'Triveni Nagar', 'Pushpa Park', 'Shivaji Nagar Malad East', 'Upper Govind Nagar', 'Primal Nagar', 'Dindoshi', 'Kokani Pada', 'Dhanji Wadi', 'Pathan Wadi Chowk', 'Dombivli West', 'Kopargaon', 'Mahim West', 'Asavari', 'Mahim East', 'Mahalaxmi Race Course', 'Lower Parel West', 'Chembur West', 'Rahul Nagar Chembur', 'Lower Parel East', 'Khar West', 'Juhu Koliwada', 'Old Khar', 'Khar Danda', 'Danda', 'Khar East', 'Golibar', 'RPF Colony', 'Kandivali West', 'Mahavir Nagar', 'Mahatama Gandhi Road Amrut Nagar', 'Dhanukar Wadi', 'Charkop Sector 2', 'Irani Wada', 'Charkop Sector 5', 'Charkop Industrial Estate', 'Charkop Sector 7', 'Charkop', 'Bander Pakhadi', 'Charkop Sector 4', 'Charkop Sector 9', 'Charkop Sector 3', 'Charkop Village', 'Charkop Sector 8', 'Charkop Sector 6', 'Charkop Sector 1', 'Jethava Nagar', 'Ekta Nagar Charkop', 'Shankar Pada', 'Goraswadi', 'Patel Nagar', 'Ganesh Nagar JJC Area', 'Fateh Baug', 'Kandivali East', 'Lokhandwala Twp', 'Alika Nagar', 'Thakur Village, Kandivali East', 'Akurli Nagar', 'Samata Nagar', 'Ashok Nagar Western Mumbai', 'Thakur Complex', 'Asha Nagar', 'Gautam Nagar', 'Appa Pada', 'Damodarwadi', 'Dattani Park', 'Singh Aghri Estate', 'Amboli', 'Laxmi Industrial Estate', 'Andheri West', 'Lokhandwala Complex', 'Four Bungalows', 'Seven Bungalows', 'Veera Desai Road', '4 Bunglows', 'Lallu Bhai Park', 'Azad Nagar 2', 'Versova Marg', 'DN Nagar', 'D.N. Nagar', 'Shri Swami Samarth Nagar', 'Millat Nagar', 'Gilbert Hill JJC', 'SV Patel Nagar', 'Shastri Nagar D Phase', 'Navneeth Colony', 'Sundervan Complex', 'Dattaguru nagar', 'Andheri East', 'Marol', 'Chakala', 'Marol Naka', 'Saki Vihar Road', 'JB Nagar', 'Poonam Nagar', 'Marol Maroshi Road', 'Asalfa Village JJC', 'Sher E Punjab Society', 'Sakinaka Junction', 'Kadam Wadi Marol', 'Seepz Area', 'Chakala MIDC', 'Dr Charatsingh Colony', 'Malpa Dongri', 'Gondavali Gaothan', 'Sahar Village', 'Kajuwadi', 'Marol Maroshi', 'PMGP Colony', 'Customs Colony', 'Mogra Village Road', 'Kanti Nagar', 'Bamandaya Pada', 'Koladongri', 'Mogra Village', 'Jijamata Road', 'Hanuman Nagar', 'Azad Nagar JJC', 'Parsi Wada', 'Marol Naka Junction', 'Bhavani Nagar', 'Maheshwari Nagar', 'Kondivita Village']"

In [35]:
df[df['Description/Amenities'].str.contains('prime location', case=False)]

,ID,Possession Status,Developer,Units Available,Price,Price (English),Covered Area,Price per square feet,Area Name,Unit of Carpet Area,...,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,Description/Amenities
0,12685,Under Construction,Local,1.0,3150000.0,31.5 Lac,635.0,4960.0,Kalyan West,Sq-ft,...,"Library And Business Centre,","Meditation Area,","Multipurpose Courts,","Recreational Pool,","Rentable CommuniPfty Space,","Retail Boulevard (Retail Shops),","Cycling & Jogging Track,","Fire Fighting Equipment,","Aesthetically designed landscape garden,","Society, Unfurnished New Property 5 of 14 Fl..."
1,12684,Ready to Move,TATA Housing Development Company Ltd.,10.0,6300000.0,63 Lac,579.0,10880.0,Kalyan West,Sq-ft,...,"Library And Business Centre,","Meditation Area,","Multipurpose Courts,","Recreational Pool,","Rentable CommuniPfty Space,","Retail Boulevard (Retail Shops),","Cycling & Jogging Track,","Fire Fighting Equipment,","Aesthetically designed landscape garden,","Society, Unfurnished New Property 20 of 34 F..."
2,12683,Ready to Move,Sai Satyam Developers,0.0,5400000.0,54 Lac,850.0,6352.0,Kalyan West,Sq-ft,...,"Library And Business Centre,","Meditation Area,","Multipurpose Courts,","Recreational Pool,","Rentable CommuniPfty Space,","Retail Boulevard (Retail Shops),","Cycling & Jogging Track,","Fire Fighting Equipment,","Aesthetically designed landscape garden,","Society, Unfurnished New Property 18 of 18 F..."
3,12682,Under Construction,Birla Estates,70.0,9000000.0,90 Lac,1050.0,8571.0,Kalyan West,Sq-ft,...,"Library And Business Centre,","Meditation Area,","Multipurpose Courts,","Recreational Pool,","Rentable CommuniPfty Space,","Retail Boulevard (Retail Shops),","Cycling & Jogging Track,","Fire Fighting Equipment,","Aesthetically designed landscape garden,","Society, Unfurnished New Property 5 of 27 Fl..."
4,12681,Under Construction,Godrej Properties,1.0,4950000.0,49.5 Lac,561.0,8824.0,Kalyan West,Sq-ft,...,"Library And Business Centre,","Meditation Area,","Multipurpose Courts,","Recreational Pool,","Rentable CommuniPfty Space,","Retail Boulevard (Retail Shops),","Cycling & Jogging Track,","Fire Fighting Equipment,","Aesthetically designed landscape garden,","Society, Semi-Furnished New Property 8 of 26..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12330,6,Ready to Move,Atul Projects,1.0,18709662.0,1.87 Cr,891.0,20998.0,Andheri East,Sq-ft,...,,,,,,,,,,Unfurnished New Property 4 of 7 Floor Apartm...
12331,4,Under Construction,Kalpataru Ltd.,20.0,31000000.0,3.10 Cr,1376.0,22529.0,Jogeshwari Vikhroli Link Road,Sq-ft,...,"Library And Business Centre,","Meditation Area,","Multipurpose Courts,","Recreational Pool,","Rentable CommuniPfty Space,","Retail Boulevard (Retail Shops),","Cycling & Jogging Track,","Fire Fighting Equipment,","Aesthetically designed landscape garden,","Society, Unfurnished New Property 10 of 22 F..."
12332,3,Under Construction,Kalpataru Ltd.,7.0,18500000.0,1.85 Cr,970.0,19072.0,Jogeshwari Vikhroli Link Road,Sq-ft,...,"Library And Business Centre,","Meditation Area,","Multipurpose Courts,","Recreational Pool,","Rentable CommuniPfty Space,","Retail Boulevard (Retail Shops),","Cycling & Jogging Track,","Fire Fighting Equipment,","Aesthetically designed landscape garden,","Society, Semi-Furnished New Property 5 of 22..."
12333,2,Ready to Move,Local,0.0,22000000.0,2.20 Cr,650.0,26796.0,Andheri East,Sq-ft,...,"Library And Business Centre,","Meditation Area,","Multipurpose Courts,","Recreational Pool,","Rentable CommuniPfty Space,","Retail Boulevard (Retail Shops),","Cycling & Jogging Track,","Fire Fighting Equipment,","Aesthetically designed landscape garden,","Society, Semi-Furnished Resale 1 of 7 Floor ..."
12334,1,Under Construction,VKG,2.0,18500000.0,1.85 Cr,685.0,27007.0,Andheri East,Sq-ft,...,"Library And Business Centre,","Meditation Area,","Multipurpose Courts,","Recreational Pool,","Rentable CommuniPfty Space,","Retail Boulevard (Retail Shops),","Cycling & Jogging Track,","Fire Fighting Equipment,","Aesthetically designed landscape garden,","Society, Unfurnished New Property 12 of 12 F..."

In [9]:
print(f"Use the dataframe with name df with columns {df.columns} and generate python code for")

Use the dataframe with name df with columns Index(['ID', 'Possession Status', 'Developer', 'Units Available', 'Price',
       'Price (English)', 'Covered Area', 'Price per square feet', 'Area Name',
       'Unit of Carpet Area',
       ...
       'Library And Business Centre', 'Meditation Area', 'Multipurpose Courts',
       'Recreational Pool', 'Rentable CommuniPfty Space',
       'Retail Boulevard (Retail Shops)', 'Cycling & Jogging Track',
       'Fire Fighting Equipment', 'Aesthetically designed landscape garden',
       'Description/Amenities'],
      dtype='object', length=112) and generate python code for